version: '3.9'

services:
  orderservice:
    build:
      context: ./WebApplication1
    ports:
      - "7140:80"
    container_name: order-service
    restart: unless-stopped

  orderprocessor:
    build:
      context: ./OrderProcessor
    container_name: order-processor
    restart: unless-stopped
    depends_on:
      - orderservice